### ISSUE TITLE
Exception in to_string

### ISSUE THREAD

**Issue by hendry19901990** [consulthys/logstash-input-blockchain#3]
Hello, when I try to test the plugin with ethereum using the transactions option, I've got the next error:

08:20:24.341 [[main]<blockchain] ERROR logstash.pipeline - A plugin had an unrecoverable error. Will restart this plugin.
  Plugin: <LogStash::Inputs::Blockchain protocol=>"ethereum", host=>"localhost", port=>8545, start_height=>100000, granularity=>"transaction", id=>"914548ba0e9a44d00cd34a89a01e2eded45ebc9e-1", enable_metric=>true, codec=><LogStash::Codecs::JSON id=>"json_75f68452-20b5-4eb3-a87e-2a981742466c", enable_metric=>true, charset=>"UTF-8">, interval=>0>
  Error: undefined method `to_string' for 42:Fixnum

**Comment by consulthys** [comment]
Which Logstash version are you using?

**Comment by hendry19901990** [comment]
I'm using 5.4.0, but i have added a validation in the code and resolved the problem, would you like that i send a pull request to you ?

**Comment by consulthys** [comment]
Oh yes definitely, feel free to create one ! Thanks a lot
